### ISSUE TITLE
Error inferencing

### ISSUE THREAD

**Issue by lucellent** [starrytong/SCNet#3]
Trying to inference with the provided checkpoint but getting 

TypeError: apply_model() got an unexpected keyword argument 'sample_rate'

**Comment by patriotyk** [comment]
There is bug. it expects `samplerate` without underscore. https://github.com/starrytong/SCNet/blob/e75a03e8d44c24f612fa3fcebcdbd25dacc53920/scnet/apply.py#L64

**Comment by starrytong** [comment]
I updated the inference.py and you should be able to get it back up and running again

**Comment by lucellent** [comment]
> I updated the inference.py and you should be able to get it back up and running again

Thanks both of you!
There's also another small typo - it's said that in the inference code the output is "--output_path" but it should be "--output_dir"
