### ISSUE TITLE
Training model with target source

### ISSUE THREAD

**Issue by lyndonlauder** [starrytong/SCNet#4]
Hello thank you for releasing training and inference code. 

In Demucs it is possible to train the model to target one source with the Weights arg (https://github.com/facebookresearch/demucs/blob/e976d93ecc3865e5757426930257e200846a520a/conf/config.yaml#L58)

Please can you tell me if this is possible with SCNet and how i can do this?

**Comment by starrytong** [comment]
Change config.yaml.
```bash
model:
  sources: ['vocals']
``` 

Change solver. py
```bash
            sources = sources.to(self.device)
            if train:
                sources = self.augment(sources)
                mix = sources.sum(dim=1)

                # data.sources: ['drums', 'bass', 'other', 'vocals']    ---vocal_idx=4
                sources = sources[:, idx-1:idx]
            else:
                mix = sources[:, 0]
                # sources = sources[:, 1:]

                sources = sources[:, idx:idx+1]  
```

**Comment by starrytong** [comment]
This is just a piece of pseudo code. “idx” has been used in the previous code，you need to redefine a variable.
