### ISSUE TITLE
Scnet-large config

### ISSUE THREAD

**Issue by 256Bab** [starrytong/SCNet#5]
Hi

Thanks for making the code public along with your pertained weights.

I read in the paper there is Scnet and Scnet-large but the repository  only contains the config.yaml for the small scent

**Could you share the config.yaml you used to train Scnet-large?**

Thank you

**Comment by KimberleyJensen** [comment]
Large config is here https://github.com/starrytong/SCNet/blob/7bb1cccef35519f5a48de95c8cc3b739af351304/scnet/SCNet.py#L250

**Comment by starrytong** [comment]
dims = [4, 64, 128, 256]
and
band_SR = [0.225, 0.372, 0.403]

**Comment by 256Bab** [comment]
Thank you!
