### ISSUE TITLE
Intermediate training checkpoint filesizes too large?

### ISSUE THREAD

**Issue by ari-ruokamo** [starrytong/SCNet#6]
Thanks for your amazing work! ML-beginner here - but I have doubts that I've not configured the Accelerator correctly for my training. 

I'm training on musdb18hq (bass, vocals, other, drums) and I get checkpoint save-sizes almost 10-times the filesize vs. the sample checkpoint file you have provided. Is there anything to check in the Accelerator init/config to mitigate this issue?

**Comment by patriotyk** [comment]
For inference you just need "state_dict" object form the model. So you can extract this object and save to a file.

**Comment by ari-ruokamo** [comment]
Ok I see there's a lot of intermediate data in that file container - I may close this ticket.
